<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Sector;
use App\Models\Civility;
use App\Models\Location;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run()
    {
        \App\Models\Organisation::factory(10)->create();
        \App\Models\Person::factory(10)->create();
        
        $civilities=[
            ['gender'=>"Madame"],
            ['gender'=>"Monsieur"],
            ['gender'=>"Autre"],
        ];
        foreach($civilities as $civility){
            Civility::create($civility);
        }

        $sectors=[
            ['sector_name'=>"Agro-alimentaire (production)"],
            ['sector_name'=>"Architecture et urbanisme"],
            ['sector_name'=>"Assurances"],
            ['sector_name'=>"Auto / Moto - carrosserie"],
            ['sector_name'=>"Auto / Moto - concession"],
            ['sector_name'=>"Auto / Moto - multi-services"],
            ['sector_name'=>"Autres secteurs inclassables"],
            ['sector_name'=>"Avocats"],
            ['sector_name'=>"Banque"],
            ['sector_name'=>"Bureau d'étude / Ingénierie"],
            ['sector_name'=>"BTP - Autre 2nd œuvre"],
            ['sector_name'=>"BTP - Chauffage / Ventilation / Climatisation"],
            ['sector_name'=>"BTP - Couverture zinguerie"],
            ['sector_name'=>"BTP - Électricité / Domotique"],
            ['sector_name'=>"BTP - Gros œuvre / Construction / Charpente"],
            ['sector_name'=>"BTP - Menuiserie"],
            ['sector_name'=>"BTP - Non spécifique"],
            ['sector_name'=>"BTP - Peinture / Sols / Cloisons"],
            ['sector_name'=>"BTP - Produits et équipements"],
            ['sector_name'=>"BTP - Tous corps d'état"],
            ['sector_name'=>"CHR - Hôtellerie et hébergement"],
            ['sector_name'=>"CHR - Restaurants"],
            ['sector_name'=>"Commerce - Cigarette électronique"],
            ['sector_name'=>"Commerce - Cordonnerie / Serrurerie"],
            ['sector_name'=>"Commerce - Cuisines"],
            ['sector_name'=>"Commerce - Hors réseau"],
            ['sector_name'=>"Commerce - Luxe et bijouterie"],
            ['sector_name'=>"Commerce - Produits maison (meubles, mobilier, etc)"],
            ['sector_name'=>"Commerce - Réseau"],
            ['sector_name'=>"Commerce - Retail divers"],
            ['sector_name'=>"Commerce - Santé / Forme / Bien être"],
            ['sector_name'=>"Comptabilité"],
            ['sector_name'=>"Conseil (autres)"],
            ['sector_name'=>"Cosmétiques"],
            ['sector_name'=>"Courtage en crédit / Financement"],
            ['sector_name'=>"Déménagement / Garde-Meubles"],
            ['sector_name'=>"Diagnostic Immobilier"],
            ['sector_name'=>"Divertissements / Loisirs / Sports - activité"],
            ['sector_name'=>"Divertissements / Loisirs / Sports - équipement"],
            ['sector_name'=>"E-commerce"],
            ['sector_name'=>"Entreposage, stockage"],
            ['sector_name'=>"Environnement / Énergies renouvelables"],
            ['sector_name'=>"Esthétique / Cosmétique (hors commerce)"],
            ['sector_name'=>"Fonds d'investissement"],
            ['sector_name'=>"Formation primaire / secondaire privée"],
            ['sector_name'=>"Formation professionnelle"],
            ['sector_name'=>"Gestion de patrimoine"],
            ['sector_name'=>"Grande distribution généraliste"],
            ['sector_name'=>"Grande distribution spécialisée"],
            ['sector_name'=>"Immobilier"],
            ['sector_name'=>"Industrie - Chaudronnerie / Métallerie"],
            ['sector_name'=>"Industrie - Imprimerie / Reproduction"],
            ['sector_name'=>"Industrie chimique"],
            ['sector_name'=>"Industrie composants électriques/électroniques"],
            ['sector_name'=>"Industrie non spécifique"],
            ['sector_name'=>"Interim"],
            ['sector_name'=>"Logistique et chaine d'approvisionnement"],
            ['sector_name'=>"Machines et équipements"],
            ['sector_name'=>"Marketing, Communication et publicité"],
            ['sector_name'=>"Matériel Agricole"],
            ['sector_name'=>"Médias (tous types)"],
            ['sector_name'=>"Médical - Equipements / Dispositifs médicaux"],
            ['sector_name'=>"Médical - Services"],
            ['sector_name'=>"Négoce biens et équipements pour les entreprises"],
            ['sector_name'=>"Négoce / Commerce de gros"],
            ['sector_name'=>"Nettoyage industriel"],
            ['sector_name'=>"Paysage / Entretien espaces verts"],
            ['sector_name'=>"Petite enfance - Crèches et micro-crèches"],
            ['sector_name'=>"Petite enfance - Divers"],
            ['sector_name'=>"Piscine (vente/construction)"],
            ['sector_name'=>"Pharmacie"],
            ['sector_name'=>"Photovoltaïque"],
            ['sector_name'=>"Pompes Funèbres"],
            ['sector_name'=>"Pressing / Blanchisserie"],
            ['sector_name'=>"Production - Biens et équipements collectivités"],
            ['sector_name'=>"Production - Biens et équipements entreprises"],
            ['sector_name'=>"Production - Biens et équipements particuliers"],
            ['sector_name'=>"Production - Confection et mode"],
            ['sector_name'=>"Produits grand public"],
            ['sector_name'=>"Réseaux / Cablage / Fibre"],
            ['sector_name'=>"RH / Recrutement / Paie"],
            ['sector_name'=>"SAAD - Services d'Aide et Accomp. à Dom"],
            ['sector_name'=>"Santé, forme et bien-être"],
            ['sector_name'=>"Secrétariat / Accueil / Conciergerie"],
            ['sector_name'=>"Secteur Nautique"],
            ['sector_name'=>"Sécurité et gardiennage"],
            ['sector_name'=>"Sécurité informatique et des réseaux"],
            ['sector_name'=>"Services à la personne"],
            ['sector_name'=>"Services aux entreprises"],
            ['sector_name'=>"Services aux particuliers (divers)"],
            ['sector_name'=>"Techno - Edition Logiciels - Applis"],
            ['sector_name'=>"Techno - Équipement informatique"],
            ['sector_name'=>"Techno - Sécurité / Maintenance informatique"],
            ['sector_name'=>"Techno - Non spécifique"],
            ['sector_name'=>"Techno - Vente et Intégration logiciels"],
            ['sector_name'=>"Techno - Web agency / SEO-SEA"],
            ['sector_name'=>"Traduction / Correction et prestations annexes"],
            ['sector_name'=>"Transports routiers"],
            ['sector_name'=>"Verres, céramiques et ciments"],
            ['sector_name'=>"Vins et spiritueux"],
            ['sector_name'=>"Voyages et tourisme"],
        ];

        foreach($sectors as $sector){
            Sector::create($sector);
        }

        $locations =[
            ['id' => '01', 'location_name' => '01 - Ain'],
            ['id' => '02', 'location_name' => '02 - Aisne'],
            ['id' => '03', 'location_name' => '03 - Allier'],
            ['id' => '04', 'location_name' => '04 - Alpes-de-Hautes-Provence'],
            ['id' => '05', 'location_name' => '05 - Hautes-Alpes'],
            ['id' => '06', 'location_name' => '06 - Alpes-Maritimes'],
            ['id' => '07', 'location_name' => '07 - Ardèche'],
            ['id' => '08', 'location_name' => '08 - Ardennes'],
            ['id' => '09', 'location_name' => '09 - Ariège'],
            ['id' => '10', 'location_name' => '10 - Aube'],
            ['id' => '11', 'location_name' => '11 - Aude'],
            ['id' => '12', 'location_name' => '12 - Aveyron'],
            ['id' => '13', 'location_name' => '13 - Bouches-du-Rhône'],
            ['id' => '14', 'location_name' => '14 - Calvados'],
            ['id' => '15', 'location_name' => '15 - Cantal'],
            ['id' => '16', 'location_name' => '16 - Charente'],
            ['id' => '17', 'location_name' => '17 - Charente-Maritime'],
            ['id' => '18', 'location_name' => '18 - Cher'],
            ['id' => '19', 'location_name' => '19 - Corrèze'],
            ['id' => '20', 'location_name' => '20 - Corse'],
            ['id' => '21', 'location_name' => '21 - Côte-d\'or'],
            ['id' => '22', 'location_name' => '22 - Côtes-d\'Armor'],
            ['id' => '23', 'location_name' => '23 - Creuse'],
            ['id' => '24', 'location_name' => '24 - Dordogne'],
            ['id' => '25', 'location_name' => '25 - Doubs'],
            ['id' => '26', 'location_name' => '26 - Drôme'],
            ['id' => '27', 'location_name' => '27 - Eure'],
            ['id' => '28', 'location_name' => '28 - Eure-et-Loir'],
            ['id' => '29', 'location_name' => '29 - Finistère'],
            ['id' => '30', 'location_name' => '30 - Gard'],
            ['id' => '31', 'location_name' => '31 - Haute-Garonne'],
            ['id' => '32', 'location_name' => '32 - Gers'],
            ['id' => '33', 'location_name' => '33 - Gironde'],
            ['id' => '34', 'location_name' => '34 - Hérault'],
            ['id' => '35', 'location_name' => '35 - Ille-et-Vilaine'],
            ['id' => '36', 'location_name' => '36 - Indre'],
            ['id' => '37', 'location_name' => '37 - Indre-et-Loire'],
            ['id' => '38', 'location_name' => '38 - Isère'],
            ['id' => '39', 'location_name' => '39 - Jura'],
            ['id' => '40', 'location_name' => '40 - Landes'],
            ['id' => '41', 'location_name' => '41 - Loir-et-Cher'],
            ['id' => '42', 'location_name' => '42 - Loire'],
            ['id' => '43', 'location_name' => '43 - Haute-Loire'],
            ['id' => '44', 'location_name' => '44 - Loire-Altlantique'],
            ['id' => '45', 'location_name' => '45 - Loiret'],
            ['id' => '46', 'location_name' => '46 - Lot'],
            ['id' => '47', 'location_name' => '47 - Lot-et-Garonne'],
            ['id' => '48', 'location_name' => '48 - Lozère'],
            ['id' => '49', 'location_name' => '49 - Maine-et-Loire'],
            ['id' => '50', 'location_name' => '50 - Manche'],
            ['id' => '51', 'location_name' => '51 - Marne'],
            ['id' => '52', 'location_name' => '52 - Haute-Marne'],
            ['id' => '53', 'location_name' => '53 - Mayenne'],
            ['id' => '54', 'location_name' => '54 - Meurthe-et-Moselle'],
            ['id' => '55', 'location_name' => '55 - Meuse'],
            ['id' => '56', 'location_name' => '56 - Morbihan'],
            ['id' => '57', 'location_name' => '57 - Moselle'],
            ['id' => '58', 'location_name' => '58 - Nièvre'],
            ['id' => '59', 'location_name' => '59 - Nord'],
            ['id' => '60', 'location_name' => '60 - Oise'],
            ['id' => '61', 'location_name' => '61 - Orne'],
            ['id' => '62', 'location_name' => '62 - Pas-de-Calais'],
            ['id' => '63', 'location_name' => '63 - Puy-de-Dome'],
            ['id' => '64', 'location_name' => '64 - Pyrénées-Atlantiques'],
            ['id' => '65', 'location_name' => '65 - Hautes-Pyrénées'],
            ['id' => '66', 'location_name' => '66 - Pyrénées-Orientales'],
            ['id' => '67', 'location_name' => '67 - Bas-Rhin'],
            ['id' => '68', 'location_name' => '68 - Haut-Rhin'],
            ['id' => '69', 'location_name' => '69 - Rhône'],
            ['id' => '70', 'location_name' => '70 - Haute-Sâone'],
            ['id' => '71', 'location_name' => '71 - Sâone-et-Loire'],
            ['id' => '72', 'location_name' => '72 - Sarthe'],
            ['id' => '73', 'location_name' => '73 - Savoie'],
            ['id' => '74', 'location_name' => '74 - Haute-Savoie'],
            ['id' => '75', 'location_name' => '75 - Paris'],
            ['id' => '76', 'location_name' => '76 - Seine-Maritime'],
            ['id' => '77', 'location_name' => '77 - Seine-et-Marne'],
            ['id' => '78', 'location_name' => '78 - Yvelines'],
            ['id' => '79', 'location_name' => '79 - Deux-Sèvres'],
            ['id' => '80', 'location_name' => '80 - Somme'],
            ['id' => '81', 'location_name' => '81 - Tarn'],
            ['id' => '82', 'location_name' => '82 - Tarn-et-Garonne'],
            ['id' => '83', 'location_name' => '83 - Var'],
            ['id' => '84', 'location_name' => '84 - Vaucluse'],
            ['id' => '85', 'location_name' => '85 - Vendée'],
            ['id' => '86', 'location_name' => '86 - Vienne'],
            ['id' => '87', 'location_name' => '87 - Haute-Vienne'],
            ['id' => '88', 'location_name' => '88 - Vosges'],
            ['id' => '89', 'location_name' => '89 - Yonne'],
            ['id' => '90', 'location_name' => '90 - Territoire de Belfort'],
            ['id' => '91', 'location_name' => '91 - Essonne'],
            ['id' => '92', 'location_name' => '92 - Hauts-de-Seine'],
            ['id' => '93', 'location_name' => '93 - Seine-Saint-Denis'],
            ['id' => '94', 'location_name' => '94 - Val-de-Marne'],
            ['id' => '95', 'location_name' => '95 - Val-d\'Oise'],
            ['id' => '99', 'location_name' => 'Hors-France'],
            ['id' => '971', 'location_name' => '971 - Guadeloupe'],
            ['id' => '972', 'location_name' => '972 - Martinique'],
            ['id' => '973', 'location_name' => '973 - Guyane Française'],
            ['id' => '974', 'location_name' => '974 - Réunion'],
            ['id' => '975', 'location_name' => '975 - Saint-Pierre et Miquelon'],
            ['id' => '976', 'location_name' => '976 - Mayotte'],
            ['id' => '977', 'location_name' => '977 - Saint-Barthélemy'],
            ['id' => '978', 'location_name' => '978 - Saint-Martin'],
        ];
        foreach($locations as $location){
            Location::create($location);
        }
    }
}
